###problems
POST http://localhost:5000/problems
Content-Type: application/json

{
  "title":"Add Two Numbers",
  "description":"Given two numbers return their sum",
  "difficulty":"Easy",
  "testCases":[
    {
      "input":"2 3",
      "expectedOutput":"5"
    },
    {
      "input":"10 20",
      "expectedOutput":"30"
    }
  ]
}

###get probs
GET http://localhost:5000/problems


###get particular prob
GET http://localhost:5000/problems/6a2b9fb1d17c4dc7c4a366e4

###submit
POST http://localhost:5000/submit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTIzYjMwNjVhM2QzYmNmMWQ1ZDU1ZTMiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzgxMjU4ODk0LCJleHAiOjE3ODE4NjM2OTR9.S986MXdKIcEGpfr4gd57_p4oXtN9XlT7Gl5odLdZ7ko

{
  "problemId": "6a2b9b25a9a22bd3727f084e",
  "language": "python",
  "code": "import sys\ndef is_palindrome(s: str):\n    cleaned = ''.join(c.lower() for c in s if c.isalnum())\n    return str(cleaned == cleaned[::-1]).lower()\nif __name__ == '__main__':\n    input_data = sys.stdin.read().strip()\n    print(is_palindrome(input_data))"
}

###register
POST http://localhost:5000/register
Content-Type: application/json

{
  "username":"nani",
  "email":"nani@test.com",
  "password":"123456"
}


###login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email":"sam@test.com",
  "password":"123456"
}


###submissions
GET http://localhost:5000/submissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTIzYjMwNjVhM2QzYmNmMWQ1ZDU1ZTMiLCJpYXQiOjE3ODA4MjI5OTEsImV4cCI6MTc4MTQyNzc5MX0.Mb1zvafb5WXH_VIWnfJ6IMW7a7bYPhqii57IrXM6IOU


###profile
GET http://localhost:5000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTIzYjMwNjVhM2QzYmNmMWQ1ZDU1ZTMiLCJpYXQiOjE3ODA4MjI5OTEsImV4cCI6MTc4MTQyNzc5MX0.Mb1zvafb5WXH_VIWnfJ6IMW7a7bYPhqii57IrXM6IOU

###leaderboard
GET http://localhost:5000/leaderboard

###test js
GET http://localhost:5000/test-js


